
datasource:
  database1:
    jdbc-url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234

  database2:
    jdbc-url: jdbc:postgresql://localhost:5432/database2
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234

  database3:
    jdbc-url: jdbc:postgresql://localhost:5432/database3
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
